class COMMAND:
    CMD_MOTOR = "CMD_MOTOR"
    CMD_LED = "CMD_LED"
    CMD_LED_MOD = "CMD_LED_MOD"
    CMD_SERVO = "CMD_SERVO"
    CMD_BUZZER = "CMD_BUZZER"
    CMD_SONIC = "CMD_SONIC"
    CMD_LIGHT = "CMD_LIGHT"
    CMD_POWER = "CMD_POWER" 
    CMD_MODE ="CMD_MODE"
    CMD_LED_PATH ="CMD_LED_PATH"
    CMD_SEQ = "CMD_SEQ"
    CMD_INFRA = "CMD_INFRA"
    CMD_PHASE = "CMD_PHASE"
    CMD_SD = "CMD_SD"
    def __init__(self):
        pass
